---
- name: install packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - mysql-server
    - python-mysqldb

- name: create root
  mysql_user:
    name={{ mysql_user }}
    password={{ mysql_pass }}
    host={{ item }}
    login_user={{ mysql_user }}
    login_password={{ mysql_pass }}
    check_implicit_admin=yes
    state=present
    priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
