"""empty message

Revision ID: 177647224e96
Revises: 403e906b8a84
Create Date: 2015-03-16 16:00:10.689499

"""

# revision identifiers, used by Alembic.
revision = '177647224e96'
down_revision = '403e906b8a84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
