"""empty message

Revision ID: 3201013a368a
Revises: 33412106cdda
Create Date: 2014-10-14 10:06:22.880985

"""

# revision identifiers, used by Alembic.
revision = '3201013a368a'
down_revision = '33412106cdda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('uploaded_for', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'uploaded_for')
    ### end Alembic commands ###
