"""empty message

Revision ID: 36532a52722f
Revises: None
Create Date: 2015-03-13 10:32:54.566392

"""

# revision identifiers, used by Alembic.
revision = '36532a52722f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(length=700), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_metadata',
    sa.Column('ct_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=700), nullable=True),
    sa.Column('twitter', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('ct_id')
    )
    op.create_table('prayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('show_user', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_metadata',
    sa.Column('ct_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('ct_id')
    )
    op.create_table('images',
    sa.Column('uuid', sa.String(length=120), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('upload_to', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_metadata.ct_id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('group_metadata')
    op.drop_table('prayers')
    op.drop_table('user_metadata')
    op.drop_table('news')
    ### end Alembic commands ###
