"""empty message

Revision ID: 3e5360da8368
Revises: 478b739deeb9
Create Date: 2015-03-30 10:17:20.769022

"""

# revision identifiers, used by Alembic.
revision = '3e5360da8368'
down_revision = '478b739deeb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_row_image', sa.String(length=120), nullable=True),
    sa.Column('first_row_link', sa.String(length=120), nullable=True),
    sa.Column('second_row_image', sa.String(length=120), nullable=True),
    sa.Column('second_row_link', sa.String(length=120), nullable=True),
    sa.Column('third_row_left_image', sa.String(length=120), nullable=True),
    sa.Column('third_row_left_link', sa.String(length=120), nullable=True),
    sa.Column('third_row_right_image', sa.String(length=120), nullable=True),
    sa.Column('third_row_right_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frontpage')
    ### end Alembic commands ###
