"""empty message

Revision ID: 3ea2b50a38f4
Revises: 82eb7f202b8
Create Date: 2014-09-29 17:20:46.381387

"""

# revision identifiers, used by Alembic.
revision = '3ea2b50a38f4'
down_revision = '82eb7f202b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('pub_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'pub_date')
    ### end Alembic commands ###
