"""empty message

Revision ID: 403e906b8a84
Revises: 36532a52722f
Create Date: 2015-03-16 15:27:28.843041

"""

# revision identifiers, used by Alembic.
revision = '403e906b8a84'
down_revision = '36532a52722f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('prayers', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayers', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('prayers', 'user_id')
    ### end Alembic commands ###
