"""empty message

Revision ID: 40c0e08f7d2f
Revises: 347834148c1f
Create Date: 2014-10-15 11:56:49.543830

"""

# revision identifiers, used by Alembic.
revision = '40c0e08f7d2f'
down_revision = '347834148c1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=True),
    sa.Column('show_user', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prayers')
    ### end Alembic commands ###
