"""empty message

Revision ID: 478b739deeb9
Revises: 3660fb105f1
Create Date: 2015-03-19 09:17:11.542768

"""

# revision identifiers, used by Alembic.
revision = '478b739deeb9'
down_revision = '3660fb105f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsup', sa.Column('active', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsup', 'active')
    ### end Alembic commands ###
