"""empty message

Revision ID: 482aae51616c
Revises: 40c0e08f7d2f
Create Date: 2014-11-13 13:00:46.679404

"""

# revision identifiers, used by Alembic.
revision = '482aae51616c'
down_revision = '40c0e08f7d2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
