"""empty message

Revision ID: 4ca578cad970
Revises: None
Create Date: 2014-09-18 13:12:35.381337

"""

# revision identifiers, used by Alembic.
revision = '4ca578cad970'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('where', sa.String(length=255), nullable=True),
    sa.Column('when', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('long_description', sa.String(length=700), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('image', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('long_description'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_description'),
    sa.UniqueConstraint('when'),
    sa.UniqueConstraint('where')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    op.drop_table('roles_users')
    op.drop_table('groups')
    op.drop_table('roles')
    op.drop_table('users')
    ### end Alembic commands ###
