"""empty message

Revision ID: 4e6f542c9d30
Revises: 566923beeedb
Create Date: 2015-03-17 11:57:22.460102

"""

# revision identifiers, used by Alembic.
revision = '4e6f542c9d30'
down_revision = '566923beeedb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsup', sa.Column('pub_date', sa.DateTime(), nullable=True))
    op.add_column('whatsup_comments', sa.Column('pub_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsup_comments', 'pub_date')
    op.drop_column('whatsup', 'pub_date')
    ### end Alembic commands ###
