"""empty message

Revision ID: 566923beeedb
Revises: 177647224e96
Create Date: 2015-03-17 10:45:06.105701

"""

# revision identifiers, used by Alembic.
revision = '566923beeedb'
down_revision = '177647224e96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_metadata.ct_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsup_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['whatsup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_metadata.ct_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsup_comments')
    op.drop_table('whatsup')
    ### end Alembic commands ###
