"""empty message

Revision ID: 82eb7f202b8
Revises: 4ca578cad970
Create Date: 2014-09-29 17:10:42.679890

"""

# revision identifiers, used by Alembic.
revision = '82eb7f202b8'
down_revision = '4ca578cad970'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    ### end Alembic commands ###
